#!/usr/bin/env node
/**
 * discover-ats.mjs — find which public ATS each target employer uses.
 *
 * Probes candidate slugs against the public job-board APIs of Greenhouse, Lever,
 * SmartRecruiters, Ashby and Workable, and writes the confirmed hits to
 * ats-feeds.json for fetch-ats.mjs to consume. All free, no API keys.
 *
 * Run it once, then occasionally -- employers do migrate ATS.
 *
 *   node discover-ats.mjs           # probe all, merge into ats-feeds.json
 *   node discover-ats.mjs --dry     # probe and print only
 *
 * INPUT: employers.json (copy employers.example.json). One entry per employer
 * with candidate slugs. Guessing is cheap, so list several spellings.
 *
 * NOTE: many large employers use Workday, which needs a different probe --
 * see discover-workday.mjs.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'ats-feeds.json');
const IN = existsSync(join(HERE, 'employers.json')) ? join(HERE, 'employers.json') : join(HERE, 'employers.example.json');
const DRY = process.argv.includes('--dry');
const TIMEOUT_MS = 12000;
const CONCURRENCY = 12;

const TARGETS = JSON.parse(readFileSync(IN, 'utf8')).employers || [];
if (IN.endsWith('employers.example.json')) {
  console.error('discover-ats: using employers.example.json. Copy it to employers.json and put your own target employers in it.');
}

const ATS = {
  greenhouse: {
    url: (s) => `https://boards-api.greenhouse.io/v1/boards/${s}/jobs`,
    count: (j) => (Array.isArray(j?.jobs) ? j.jobs.length : null),
  },
  lever: {
    url: (s) => `https://api.lever.co/v0/postings/${s}?mode=json`,
    count: (j) => (Array.isArray(j) ? j.length : null),
  },
  smartrecruiters: {
    url: (s) => `https://api.smartrecruiters.com/v1/companies/${s}/postings?limit=1`,
    count: (j) => (typeof j?.totalFound === 'number' ? j.totalFound : null),
  },
  ashby: {
    url: (s) => `https://api.ashbyhq.com/posting-api/job-board/${s}`,
    count: (j) => (Array.isArray(j?.jobs) ? j.jobs.length : null),
  },
  workable: {
    url: (s) => `https://apply.workable.com/api/v1/widget/accounts/${s}?details=true`,
    count: (j) => (Array.isArray(j?.jobs) ? j.jobs.length : null),
  },
};

async function probe(ats, slug) {
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(ATS[ats].url(slug), { signal: ctl.signal, headers: { 'User-Agent': 'jobscan/1.0' } });
    if (!res.ok) return null;
    const j = JSON.parse(await res.text());
    const n = ATS[ats].count(j);
    return typeof n === 'number' ? n : null;
  } catch { return null; } finally { clearTimeout(t); }
}

const work = [];
for (const { employer, sector, slugs } of TARGETS) {
  for (const slug of slugs || []) for (const ats of Object.keys(ATS)) work.push({ employer, sector, ats, slug });
}

console.error(`Probing ${work.length} (employer, ats, slug) combinations...`);
const found = [];
let i = 0;
async function worker() {
  while (i < work.length) {
    const item = work[i++];
    const n = await probe(item.ats, item.slug);
    if (n !== null && n > 0) {
      found.push({ ...item, jobCount: n });
      console.error(`  HIT  ${item.employer} -> ${item.ats}/${item.slug} (${n} jobs)`);
    }
  }
}
await Promise.all(Array.from({ length: CONCURRENCY }, worker));

// Keep the richest feed per employer.
const best = new Map();
for (const f of found) {
  const prev = best.get(f.employer);
  if (!prev || f.jobCount > prev.jobCount) best.set(f.employer, f);
}

const existing = existsSync(OUT) ? JSON.parse(readFileSync(OUT, 'utf8')) : { feeds: [] };
// Preserve Workday and Paylocity entries, which this script does not probe.
const preserved = (existing.feeds || []).filter((f) => f.ats === 'workday' || f.ats === 'paylocity');

const registry = {
  _comment: 'Employer -> public ATS job-feed registry. Generated by discover-ats.mjs / discover-workday.mjs. Consumed by fetch-ats.mjs.',
  generated: new Date().toISOString().slice(0, 10),
  keywords: existing.keywords || ['analyst', 'scientist', 'manager', 'specialist'],
  feeds: [...preserved, ...[...best.values()].map(({ employer, sector, ats, slug, jobCount }) => ({ employer, sector, ats, slug, jobCount }))]
    .sort((a, b) => a.employer.localeCompare(b.employer)),
};

const missing = TARGETS.map((t) => t.employer).filter((e) => !best.has(e));
console.error(`\nConfirmed ${best.size} of ${TARGETS.length} employers.`);
console.error(`No public feed for ${missing.length}: ${missing.join(', ')}`);
console.error('Employers missing here are often on Workday -- try discover-workday.mjs next.');

if (DRY) console.log(JSON.stringify(registry, null, 2));
else { writeFileSync(OUT, JSON.stringify(registry, null, 2) + '\n'); console.error(`\nWrote ${OUT}`); }
